### ISSUE TITLE
data overrided problem with dali backend

### ISSUE THREAD

**Issue by LightToYang** [triton-inference-server/dali_backend#39] opened 2021-03-17 08:10 UTC
I met the problem described in triton-inference-server/server#2616.
After swithing to nvcr.io/nvidia/tritonserver:21.02-py3 and following the Known limitations

`Due to DALI limitations, you might observe unnaturally increased memory consumption when defining instance group for DALI model with higher count than 1. We suggest using default instance group for DALI model.`

I find something strange about dali backend, the repeated face feature number increased as dali backend instance decreased, for examples:

**python grpc client infer with single thread**
```
1 dali backend instances
embedding_array: (11190, 512)
unmatch_num/total_num: 0/11190
```

**python grpc client infer with thread pool (simulate high concurrency situation)**
```
1 dali backend instances
embedding_array: (11190, 512)
unmatch_num/total_num: 7246/11190

2 dali backend instances
embedding_array: (11190, 512)
unmatch_num/total_num: 4040/11190

4 dali backend instances
embedding_array: (11190, 512)
unmatch_num/total_num: 1628/11190

8 dali backend instances
embedding_array: (11190, 512)
unmatch_num/total_num: 64/11190
```

so I wonder whether there is some kind of data overrided problem in dali backend ？

**Comment by banasraf** [comment] 2021-03-25 09:19
Hello @LightToYang, I responded to you in triton-inference-server/server#2616 
It's not clear for me if the problem happens on the server side or the client side.

**Comment by szalpal** [comment] 2021-04-27 08:10
Closing as duplicate. Please reopen with additional information if the issue is not resolved

**Closed by szalpal** 2021-04-27 08:10 UTC
Labels: question
